/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as PiAgentRouteImport } from './routes/pi-agent'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsItemIdRouteImport } from './routes/collections.$itemId'
import { Route as DecisionsIndexRouteImport } from './routes/decisions.index'
import { Route as DecisionsActionsRouteImport } from './routes/decisions.actions'
import { Route as DecisionsEvidenceRouteImport } from './routes/decisions.evidence'
import { Route as DecisionsExtractionRouteImport } from './routes/decisions.extraction'
import { Route as DecisionsRankingRouteImport } from './routes/decisions.ranking'
import { Route as DecisionsSkillsRouteImport } from './routes/decisions.skills'
import { Route as DecisionsTicketsRouteImport } from './routes/decisions.tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const PiAgentRoute = PiAgentRouteImport.update({
  id: '/pi-agent',
  path: '/pi-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsItemIdRoute = CollectionsItemIdRouteImport.update({
  id: '/collections/$itemId',
  path: '/collections/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsIndexRoute = DecisionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DecisionsRoute,
} as any)
const DecisionsActionsRoute = DecisionsActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => DecisionsRoute,
} as any)
const DecisionsEvidenceRoute = DecisionsEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => DecisionsRoute,
} as any)
const DecisionsExtractionRoute = DecisionsExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => DecisionsRoute,
} as any)
const DecisionsRankingRoute = DecisionsRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => DecisionsRoute,
} as any)
const DecisionsSkillsRoute = DecisionsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DecisionsRoute,
} as any)
const DecisionsTicketsRoute = DecisionsTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DecisionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRouteWithChildren
  '/pi-agent': typeof PiAgentRoute
  '/collections/$itemId': typeof CollectionsItemIdRoute
  '/decisions/actions': typeof DecisionsActionsRoute
  '/decisions/evidence': typeof DecisionsEvidenceRoute
  '/decisions/extraction': typeof DecisionsExtractionRoute
  '/decisions/ranking': typeof DecisionsRankingRoute
  '/decisions/skills': typeof DecisionsSkillsRoute
  '/decisions/tickets': typeof DecisionsTicketsRoute
  '/collections/': typeof CollectionsIndexRoute
  '/decisions/': typeof DecisionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pi-agent': typeof PiAgentRoute
  '/collections/$itemId': typeof CollectionsItemIdRoute
  '/decisions/actions': typeof DecisionsActionsRoute
  '/decisions/evidence': typeof DecisionsEvidenceRoute
  '/decisions/extraction': typeof DecisionsExtractionRoute
  '/decisions/ranking': typeof DecisionsRankingRoute
  '/decisions/skills': typeof DecisionsSkillsRoute
  '/decisions/tickets': typeof DecisionsTicketsRoute
  '/collections': typeof CollectionsIndexRoute
  '/decisions': typeof DecisionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRouteWithChildren
  '/pi-agent': typeof PiAgentRoute
  '/collections/$itemId': typeof CollectionsItemIdRoute
  '/decisions/actions': typeof DecisionsActionsRoute
  '/decisions/evidence': typeof DecisionsEvidenceRoute
  '/decisions/extraction': typeof DecisionsExtractionRoute
  '/decisions/ranking': typeof DecisionsRankingRoute
  '/decisions/skills': typeof DecisionsSkillsRoute
  '/decisions/tickets': typeof DecisionsTicketsRoute
  '/collections/': typeof CollectionsIndexRoute
  '/decisions/': typeof DecisionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decisions'
    | '/pi-agent'
    | '/collections/$itemId'
    | '/decisions/actions'
    | '/decisions/evidence'
    | '/decisions/extraction'
    | '/decisions/ranking'
    | '/decisions/skills'
    | '/decisions/tickets'
    | '/collections/'
    | '/decisions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pi-agent'
    | '/collections/$itemId'
    | '/decisions/actions'
    | '/decisions/evidence'
    | '/decisions/extraction'
    | '/decisions/ranking'
    | '/decisions/skills'
    | '/decisions/tickets'
    | '/collections'
    | '/decisions'
  id:
    | '__root__'
    | '/'
    | '/decisions'
    | '/pi-agent'
    | '/collections/$itemId'
    | '/decisions/actions'
    | '/decisions/evidence'
    | '/decisions/extraction'
    | '/decisions/ranking'
    | '/decisions/skills'
    | '/decisions/tickets'
    | '/collections/'
    | '/decisions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisionsRoute: typeof DecisionsRouteWithChildren
  PiAgentRoute: typeof PiAgentRoute
  CollectionsItemIdRoute: typeof CollectionsItemIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi-agent': {
      id: '/pi-agent'
      path: '/pi-agent'
      fullPath: '/pi-agent'
      preLoaderRoute: typeof PiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$itemId': {
      id: '/collections/$itemId'
      path: '/collections/$itemId'
      fullPath: '/collections/$itemId'
      preLoaderRoute: typeof CollectionsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/': {
      id: '/decisions/'
      path: '/'
      fullPath: '/decisions/'
      preLoaderRoute: typeof DecisionsIndexRouteImport
      parentRoute: typeof DecisionsRoute
    }
    '/decisions/actions': {
      id: '/decisions/actions'
      path: '/actions'
      fullPath: '/decisions/actions'
      preLoaderRoute: typeof DecisionsActionsRouteImport
      parentRoute: typeof DecisionsRoute
    }
    '/decisions/evidence': {
      id: '/decisions/evidence'
      path: '/evidence'
      fullPath: '/decisions/evidence'
      preLoaderRoute: typeof DecisionsEvidenceRouteImport
      parentRoute: typeof DecisionsRoute
    }
    '/decisions/extraction': {
      id: '/decisions/extraction'
      path: '/extraction'
      fullPath: '/decisions/extraction'
      preLoaderRoute: typeof DecisionsExtractionRouteImport
      parentRoute: typeof DecisionsRoute
    }
    '/decisions/ranking': {
      id: '/decisions/ranking'
      path: '/ranking'
      fullPath: '/decisions/ranking'
      preLoaderRoute: typeof DecisionsRankingRouteImport
      parentRoute: typeof DecisionsRoute
    }
    '/decisions/skills': {
      id: '/decisions/skills'
      path: '/skills'
      fullPath: '/decisions/skills'
      preLoaderRoute: typeof DecisionsSkillsRouteImport
      parentRoute: typeof DecisionsRoute
    }
    '/decisions/tickets': {
      id: '/decisions/tickets'
      path: '/tickets'
      fullPath: '/decisions/tickets'
      preLoaderRoute: typeof DecisionsTicketsRouteImport
      parentRoute: typeof DecisionsRoute
    }
  }
}

interface DecisionsRouteChildren {
  DecisionsActionsRoute: typeof DecisionsActionsRoute
  DecisionsEvidenceRoute: typeof DecisionsEvidenceRoute
  DecisionsExtractionRoute: typeof DecisionsExtractionRoute
  DecisionsRankingRoute: typeof DecisionsRankingRoute
  DecisionsSkillsRoute: typeof DecisionsSkillsRoute
  DecisionsTicketsRoute: typeof DecisionsTicketsRoute
  DecisionsIndexRoute: typeof DecisionsIndexRoute
}

const DecisionsRouteChildren: DecisionsRouteChildren = {
  DecisionsActionsRoute: DecisionsActionsRoute,
  DecisionsEvidenceRoute: DecisionsEvidenceRoute,
  DecisionsExtractionRoute: DecisionsExtractionRoute,
  DecisionsRankingRoute: DecisionsRankingRoute,
  DecisionsSkillsRoute: DecisionsSkillsRoute,
  DecisionsTicketsRoute: DecisionsTicketsRoute,
  DecisionsIndexRoute: DecisionsIndexRoute,
}

const DecisionsRouteWithChildren = DecisionsRoute._addFileChildren(
  DecisionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisionsRoute: DecisionsRouteWithChildren,
  PiAgentRoute: PiAgentRoute,
  CollectionsItemIdRoute: CollectionsItemIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
